language: scala
script:
  - sh runtests.sh
  - sbt 'project benchmark' 'run-main bignum.MultiplyBenchmark'
  - sbt 'project benchmark' 'run-main bignum.AddBenchmark'
  - sbt 'project benchmark' 'run-main bignum.ShiftBenchmark'
scala:
  - 2.10.3
  - 2.11.0-M8
jdk:
  - openjdk6
  - oraclejdk7
  - oraclejdk8
