language: scala
script:
  - sh runtests.sh
  - sbt 'project benchmark' 'run-main bignum.benchmark.MultiplyBenchmark'
  - sbt 'project benchmark' 'run-main bignum.benchmark.AddBenchmark'
  - sbt 'project benchmark' 'run-main bignum.benchmark.ShiftBenchmark'
scala:
  - 2.10.3
  - 2.11.0-RC1
jdk:
  - openjdk6
  - oraclejdk7
  - oraclejdk8
